"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
[](fg:bright-black)\
$git_branch\
$git_status\
[](fg:bright-black)\
$status\
$character"""

right_format = """
[](fg:bright-black)\
$nodejs\
$rust\
$golang\
$php\
[](fg:bright-black)\
$time\
"""

[status]
symbol = ' '
disabled = false

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[directory]
style = "fg:bright-white"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "/"

[git_branch]
symbol = ""
style = ""
format = '[[ $symbol $branch ](fg:blue)]($style)'

[git_status]
style = ""
format = '[[($conflicted$stashed$untracked$staged$deleted$renamed$modified$typechanged$ahead_behind )](fg:blue)]($style)'
conflicted = '[!](bold red)'
ahead = '[](purple)'
behind = '[](purple)'
diverged = '[](purple)'
up_to_date = ''
untracked = '[](yellow)'
stashed = '[](white)'
modified = '[](yellow)'
staged = "[](green)"
renamed = "[󰔰](green)"
deleted = "[](green)"

[nodejs]
symbol = ""
style = ""
format = '[[ $symbol ($version) ](fg:blue)]($style)'

[rust]
symbol = ""
style = ""
format = '[[ $symbol ($version) ](fg:blue)]($style)'

[golang]
symbol = ""
style = ""
format = '[[ $symbol ($version) ](fg:blue)]($style)'

[php]
symbol = ""
style = ""
format = '[[ $symbol ($version) ](fg:blue)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = ""
format = '[[ $time](fg:white)]($style)'
