"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
[](fg:#394260)\
$git_branch\
$git_status\
[](fg:#394260)\
$status\
$character"""

right_format = """
[](fg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736)\
$time\
"""

[status]
symbol = ' '
disabled = false

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[directory]
style = "fg:#e3e5e5"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "/"

[git_branch]
symbol = ""
style = ""
format = '[[ $symbol $branch ](fg:#769ff0)]($style)'

[git_status]
style = ""
format = '[[($conflicted$stashed$untracked$staged$deleted$renamed$modified$typechanged$ahead_behind )](fg:#769ff0)]($style)'
conflicted = '[!](bold red)'
ahead = '[](purple)'
behind = '[](purple)'
diverged = '[](purple)'
up_to_date = ''
untracked = '[](yellow)'
stashed = '[](white)'
modified = '[](yellow)'
staged = "[](green)"
renamed = "[󰔰](green)"
deleted = "[](green)"

[nodejs]
symbol = ""
style = ""
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[rust]
symbol = ""
style = ""
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[golang]
symbol = ""
style = ""
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[php]
symbol = ""
style = ""
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = ""
format = '[[ $time](fg:#a0a9cb)]($style)'
